---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service-externe
  namespace: sample-app-kub-namespace
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
    - name: port80
      protocol: TCP
      port: 80
      targetPort: 8080