## Ce playbook va initiliaser le cluster
### Il va se connecter au VMs Master et faire la commande :
#### sudo kubeadm init --apiserver-adverise-address=<id load balancer> --pod-network-cidr=192.168.0.0/16 --cri-socket=unix://var/run/cri-dockerd.sock
- name: Initiate Dependencies
  remote_user: root
  hosts: master
  roles:
    - init_masters
