# tasks file for roles/cluster_network
- name: Desable the taint on master node
  run: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  args:
    chdir: $HOME

- pause: seconds=30

- name: Copy file with owner and permissions
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/calico.yaml"
    dest: /home/{{ ansible_user }}/calico.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Install the network pluging to the cluster
  run: kubectl apply -f /home/{{ ansible_user }}/calico.yaml
  args:
    chdir: $HOME