name: CI Build Docker image and push

run-name: ${{ github.actor }} is launching the Build the Docker image and push it

on:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - "main"
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build-push-image-docker:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.AZURE_REGISTRY }}
          username: ${{ vars.AZURE_REGISTRY_NAME }}
          password: ${{ vars.AZURE_REGISTRY_PASSWORD }}

      - name: Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ vars.AZURE_REGISTRY }}/sample-app
          flavor: latest=true
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: sample-app/
          file: sample-app/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
