name: CI Build Docker image and push

run-name: ${{ github.actor }} is launching the Build the Docker image and push it 🚀

on:
  workflow_run:
    workflows: ["CI Build and Test"]
    types:
      - completed
  # push:
  #   branches:
  #     - dev
  #     - main

jobs:
  build-image-docker:
    runs-on: self-hosted
    steps:
      - name: Download the artefact of the app
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow: app-buil-test.yml
          workflow_conclusion: success
          name: app-tested.tar.gz
      - name: Unpack the artifact
        run: |
          rm -rf sample-app/
          mkdir sample-app/
          tar xzf app-tested.tar.gz
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZUR_REGISTRY }}
          username: ${{ secrets.AZUR_REGISTRY_NAME }}
          password: ${{ secrets.AZUR_REGISTRY_PASSWORD }}

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ secrets.AZUR_REGISTRY }}/sample-app

      - name: Print meta
        run: |
          echo "Les métadonnées pour l'image my-project sont :"
          echo ${{ steps.meta.outputs.tags }}
          echo ${{ steps.meta.outputs.labels }}
