name: CI Build Docker image and push

run-name: ${{ github.actor }} is launching the Build the Docker image and push it 🚀

on:
  workflow_run:
    workflows: ["CI Build and Test"]
    types:
      - completed
  push:
    branches:
      - dev
      - main

jobs:
  build-image-docker:
    runs-on: self-hosted
    steps:
      - name: Download the artefact of the app
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow: app-buil-test.yml
          workflow_conclusion: success
          name: app-tested.tar.gz
      - name: Remove the sample-app directory
        run: rm -rf sample-app/
      - name: Unpack the artifact
        run: |
          mkdir sample-app/
          tar xzf app-tested.tar.gz
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_DEBUG: ${{ secrets.APP_DEBUG_DOCKER }}
          envkey_APP_ENV: ${{ secrets.APP_ENV_DOCKER }}
          envkey_APP_KEY: ${{ secrets.APP_KEY }}
          envkey_APP_URL: ${{ secrets.APP_URL }}
          envkey_DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          envkey_DB_DATABASE: ${{ secrets.DB_DATABASE }}
          envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_MYSQL_ATTR_SSL_CA: ${{ secrets.KEY_PATH }}
          directory: sample-app/
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sample-app
      - name: Print meta
        run: |
          pwd && ls -al
          cd sample-app/ && ls -al
        # echo "Les métadonnées pour l'image my-project sont :"
        # echo ${{ steps.meta.outputs.tags }}
        # echo ${{ steps.meta.outputs.labels }}
