name: CI Build Docker image and push

run-name: ${{ github.actor }} is launching the Build the Docker image and push it

on:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - "main"
  push:
    # branches:
    #   - "main"
    tags:
      - "v*.*.*"

jobs:
  sniff-code:
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Install PHPStan
        run: |
          cd sample-app/
          composer require --dev phpstan/phpstan

      - name: Scan the code
        run: |
          cd sample-app/
          vendor/bin/phpstan analyse .

  build-push-image-docker:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.AZURE_REGISTRY }}
          username: ${{ vars.AZURE_REGISTRY_NAME }}
          password: ${{ vars.AZURE_REGISTRY_PASSWORD }}

      - name: Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ vars.AZURE_REGISTRY }}/sample-app
          flavor: latest=true
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: sample-app/
          file: sample-app/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
