name: CD Deploy iaas Manifeste

run-name: ${{ github.actor }} is launching the deployment of manifeste to the iaas Cluster

on:
  push:
    branches:
      - "k8s"
    paths:
      - k8s/iaas/**

jobs:
  deploy-iaas:
    name: Deploy Iaas
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v3
        with:
          version: "v1.28.6"
        id: install

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Kube config file artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: provision_iaas_infra.yml
          workflow_conclusion: success
          branch: terraform
          name: clusterConfig
          repo: ${{ github.repository }}
          check_artifacts: true
          search_artifacts: true
          skip_unpack: false
          if_no_artifact_found: fail

      - name: set up the kube config
        run: |
          mkdir ${HOME}/.kube
          mv ./config ${HOME}/.kube/config

      - name: Clone the Nginx Ingress Controller
        run: |
          git clone https://github.com/nginxinc/kubernetes-ingress.git

      - name: Install all Nginx Ingress Controller manifest
        run: |
          kubectl delete -f kubernetes-ingress/deployments/common/ns-and-sa.yaml
          kubectl delete -f kubernetes-ingress/deployments/rbac/rbac.yaml
          kubectl delete -f kubernetes-ingress/examples/shared-examples/default-server-secret/default-server-secret.yaml
          kubectl delete -f kubernetes-ingress/deployments/common/nginx-config.yaml
          kubectl delete -f k8s/iaas/ingress-class.yaml
          kubectl delete -f kubernetes-ingress/config/crd/bases/k8s.nginx.org_virtualservers.yaml
          kubectl delete -f kubernetes-ingress/config/crd/bases/k8s.nginx.org_virtualserverroutes.yaml
          kubectl delete -f kubernetes-ingress/config/crd/bases/k8s.nginx.org_virtualserverroutes.yaml
          kubectl delete -f kubernetes-ingress/config/crd/bases/k8s.nginx.org_policies.yaml
          kubectl delete -f kubernetes-ingress/config/crd/bases/k8s.nginx.org_globalconfigurations.yaml
          kubectl delete -f kubernetes-ingress/deployments/daemon-set/nginx-ingress.yaml
          kubectl delete -f kubernetes-ingress/deployments/service/nodeport.yaml

      - name: Install Cert-manager
        run: |
          kubectl delete -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml

      - name: Install Kubernetes Dashboard
        run: |
          kubectl delete -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml

      - name: Sleep for 20 seconds
        run: sleep 20s
        shell: bash

      - name: Install Kubernetes Dashboard Issuer and Ingress
        run: |
          kubectl delete -f k8s/iaas/cert-manager/issuer_sample_app_dashboard.yaml
          kubectl delete -f k8s/iaas/dashboard_ingress.yaml

      - name: Install Sample App
        run: |
          kubectl delete -f k8s/iaas/namespace.yaml
          kubectl delete -f k8s/iaas/common/
          kubectl delete -f k8s/iaas/deployement.yaml
          kubectl delete -f k8s/iaas/service_clusterip_https.yaml
          kubectl delete -f k8s/iaas/horizontalPodAutoscaler.yaml

      - name: Install Sample App Issuer and Ingress
        run: |
          kubectl delete -f k8s/iaas/cert-manager/issuer_sample_app.yaml
          kubectl delete -f k8s/iaas/ingress.yaml
