name: Pipeline deployment Infra

run-name: ${{ github.actor }} is launching the deployment of the infra

on:
  push:
    branches: [ terraform ]
  pull_request:
    branches: [ terraform ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-back-plan:
    name: Plan the TF
    runs-on: self-hosted
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run Azure CLI commands' 
        run: az --version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform test 
        run: terraform --version
      
      - name: Terraform test plan
        run: |
          pwd 
          ls

    # cd ${{ TF_ROOT }}
    # terraform init
    # terraform validate
    # terraform plan -var-file=variables.tf

    # back-apply:
    #     runs-on: self-host
