name: CD Deploy iaas Manifeste

run-name: ${{ github.actor }} is launching the deployment of manifeste to the iaas Cluster

# on:
#   push:
#     branches:
#       - "k8s"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy-AKS:
        runs-on: self-hosted
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3