name: Pipeline deployment Infra

run-name: ${{ github.actor }} is launching the deployment of the infra

on:
  push:
    branches: [ terraform ]
  pull_request:
    branches: [ terraform ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform-back-plan:
    name: Plan the TF
    runs-on: self-hosted
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli 
          az --version

      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #      creds: ${{ secrets.AZURE_CREDENTIALS }} 
          # client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # enable-AzPSSession: true 
          # allow-no-subscriptions: true

      - name: Connexion Azure
        run:
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          z account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: 'Run Azure CLI commands' 
        run: |
          az account show
          az group list
          pwd 
          
      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v2

      # - name: Terraform Init
      #   run: terraform --version

    # back-apply:
    #     runs-on: self-host
