name: CD Deploy iaas Manifeste

run-name: ${{ github.actor }} is launching the deployment of manifeste to the iaas Cluster

on:
  push:
    branches:
      - "k8s"
    # paths:
    #   - k8s/iaas/**

jobs:
  deploy-iaas:
    name: Deploy Iaas
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v3
        with:
          version: "v1.28.6"
        id: install

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Kube config file artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: provision_iaas_infra.yml
          workflow_conclusion: success
          branch: terraform
          name: clusterConfig
          repo: ${{ github.repository }}
          check_artifacts: true
          search_artifacts: true
          skip_unpack: false
          if_no_artifact_found: fail

      - name: set up the kube config
        run: |
          mkdir ${HOME}/.kube
          mv ./config ${HOME}/.kube/config

      - name: Clone the Nginx Ingress Controller
        run: |
          git clone https://github.com/nginxinc/kubernetes-ingress.git

      - name: Install all Nginx Ingress Controller manifest
        run: |
          kubectl apply -f kubernetes-ingress/deployments/common/ns-and-sa.yaml
          kubectl apply -f kubernetes-ingress/deployments/rbac/rbac.yaml
          kubectl apply -f kubernetes-ingress/examples/shared-examples/default-server-secret/default-server-secret.yaml
          kubectl apply -f kubernetes-ingress/deployments/common/nginx-config.yaml
          kubectl apply -f k8s/iaas/ingress-class.yaml
          kubectl apply -f kubernetes-ingress/config/crd/bases/k8s.nginx.org_virtualservers.yaml
          kubectl apply -f kubernetes-ingress/config/crd/bases/k8s.nginx.org_virtualserverroutes.yaml
          kubectl apply -f kubernetes-ingress/config/crd/bases/k8s.nginx.org_virtualserverroutes.yaml
          kubectl apply -f kubernetes-ingress/config/crd/bases/k8s.nginx.org_policies.yaml
          kubectl apply -f kubernetes-ingress/config/crd/bases/k8s.nginx.org_globalconfigurations.yaml
          kubectl apply -f kubernetes-ingress/deployments/daemon-set/nginx-ingress.yaml
          kubectl apply -f k8s/iaas/nginx-loadbalancer.yaml
