name: Pipeline deployment Backend

run-name: ${{ github.actor }} is launching the deployment of the tf backend

on:
  push:
    branches: [ terraform ]
    paths: # if change on the back folder this workflow will run
      - terraform/back/*

jobs:
  tf-backend-infra-plan:
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    name: Plan backend TF infra
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Use Terraform Action
        uses: hashicorp/setup-terraform@v2
      - name: Terraform backend infra plan
        run: |
          az account show
          terraform --version
          echo $GITHUB_REF_NAME